name: Sync pnpm-lock

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package-lock.json"

jobs:
  pnpm_install:
#    if: ${{ startsWith(github.ref_name, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - run: pnpm install --no-frozen-lockfile
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update pnpm lockfile
